### ISSUE TITLE
New Problems with Orbit vs Non Orbit dependencies in Platform and other Project

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.releng.aggregator#449]
with have a target with

```
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<unit id="com.google.gson" version="2.9.0.v20220704-0629"/>
			<unit id="com.google.inject" version="5.0.1.v20210324-2015"/>
			<unit id="javax.inject" version="1.0.0.v20220405-0441"/>
			<unit id="org.antlr.runtime" version="3.2.0.v20220404-1927"/>
			<unit id="org.junit" version="4.13.2.v20211018-1956"/>
			<unit id="org.apiguardian" version="1.1.2.v20211018-1956"/>
			<unit id="org.junit.jupiter.api" version="5.8.2.v20220624-2009"/>
			<unit id="org.junit.jupiter.engine" version="5.8.2.v20220624-2009"/>
			<unit id="org.junit.platform.commons" version="1.8.2.v20220624-2009"/>
			<unit id="org.junit.platform.engine" version="1.8.2.v20220624-2009"/>
			<unit id="org.junit.platform.launcher" version="1.8.2.v20220624-2009"/>
			<unit id="org.junit.platform.runner" version="1.8.2.v20220624-2009"/>
			<unit id="org.junit.platform.suite.commons" version="1.8.2.v20220624-2009"/>
			<unit id="org.opentest4j" version="1.2.0.v20211018-1956"/>
			<unit id="org.objectweb.asm" version="9.3.0.v20220409-0157"/>
			<unit id="io.github.classgraph" version="4.8.138.v20211212-1642"/>
			<repository location="https://download.eclipse.org/tools/orbit/downloads/2022-09"/>
		</location>
```

now the build is failing with

```
[ERROR]   You requested to install 'org.eclipse.equinox.p2.iu; org.junit.jupiter.migrationsupport [5.0.0,6.0.0)' but it could not be found
```

the manifest has

```
org.junit.jupiter.api;bundle-version="[5.1.0,6.0.0)",
```
+ transitive import packages on

```
 org.junit.jupiter.api;version="[5.0.0,6.0.0)";resolution:=optional,
 org.junit.jupiter.api.extension;version="[5.0.0,6.0.0)";resolution:=optional,
 org.junit.platform.commons.support;version="[1.0.0,2.0.0)";resolution:=optional
```

what has changed on platform?

similar problem for other junit5 transitive deps like `org.junit.jupiter.params`

**Comment by cdietrich** [comment]
cc @mickaelistria

**Comment by merks** [comment]
All those JUnit 5 things are coming directly from Maven and have different bundle IDs than before:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L551

**Comment by akurtakov** [comment]
Platform moved to use symbolic names of projects as their authors decided them. You'll have to update your target platform accordingly. This change reduces time spend to update dependencies and increases interoperability as everyone else but Orbit users will have junit jars with symbolic names like Platform uses now.
I'm closing this one as there is nothing to be done here on platform side.

**Comment by cdietrich** [comment]
i am still not clear that platforms guideline is
- on the one hand platform stop shipping stuff that was shipped before (like commons.io)
- on the other hand stuff is shipped with different metadata from orbits once and downstream projects can and should consume them?!?

**Comment by iloveeclipse** [comment]
@akurtakov : it would be nice at least to provide the mapping between old/new.

@cdietrich : here is it: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/380/files

If I read it right, `junit-jupiter-migrationsupport` and `junit-jupiter-params`are the new names.

PS: @cdietrich: note, in original PR was a typo, that was fixed later: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/395/files

**Comment by cdietrich** [comment]
i assume that our original problem was that the junit 5 stuff was partially pulled from orbit and partially from platform and this now no longer works cause we have a complete separate zoo of plugins and there dependencies now.
so i moved to pull everything from orbit and this seems to work.

**Comment by akurtakov** [comment]
> i am still not clear that platforms guideline is
> 
>     * on the one hand platform stop shipping stuff that was shipped before (like commons.io)
> 
>     * on the other hand stuff is shipped with different metadata from orbits once and downstream projects can and should consume them?!?

Commons IO is still shipped, what changed is the Bundle-SymbolicName. Projects using Import-Package will have to adjust only target platform, projects using Require-Bundle will have to adjust their manifests too.

> 
>     * and again it would be nice to initiate the official abolishment of orbit if this is the way eclipse is going

Orbit is not entirely dead (yet!) from my POV as there are projects (e.g. Lucene) that don't ship OSGi manifests but plain old jars, for such cases Orbit would still be used but my hope is that overtime work with upstream projects will allow to start using even these directly. 
Additionally Orbit is separate Eclipse projects so Eclipse TLP has no power to abolish it.

**Comment by akurtakov** [comment]
> i assume that our original problem was that the junit 5 stuff was partially pulled from orbit and partially from platform and this now no longer works cause we have a complete separate zoo of plugins and there dependencies now. so i moved to pull everything from orbit and this seems to work.

It may work for now but you should keep in mind that it may no longer work after the update to JUnit 5.9 which we don't plan to contribute to Orbit. Using only Orbit or only upstream symbolic names should be equally working right now but the later should be more sustainable long term.

**Comment by cdietrich** [comment]
i still dont get it, if every project does what they think, then we basically can forget having a simrel.
maybe i just should give up and pull Xtext from simrel and with it everything that depends on it. :(

**Comment by akurtakov** [comment]
There is a difference between every project doing what they think and doing what they can. Right now people doing releng for eclipse platform can not spend the extra time to contribute to Orbit. And considering the last release fiasco (https://github.com/eclipse-platform/eclipse.platform.releng/issues/50 ) with published maven artifacts breaking the world thanks to Orbit not using upstream symbolic names it's counter productive. 
Alternative solution I can see is not change a thing and let Eclipse ship with outdated, security concerned and etc. libraries. Unfortunately in that case I don't see anyone being paid to still do releng work.

**Comment by cdietrich** [comment]
what i dont understand. why not create a orbit2 in platform where ALL mavenish stuff lives and can be consumed by downsteam projects.

**Comment by akurtakov** [comment]
> what i dont understand. why not create a orbit2 in platform where ALL mavenish stuff lives and can be consumed by downsteam projects.

First of all, that would buy nothing. You can use the p2 repo and it already contains all the jars we ship.
Second, what you ask would cost non-trivial amount of time which no one is ready, willing or even see productive to spend.

**Comment by cdietrich** [comment]
yes i already understand this, but i am not sure if everybody knows what this implies: so we are back to: no more common stuff, each projects cares about themselves. and i would like to make this implicit agreement explicit

**Comment by akurtakov** [comment]
In that case we are having the discussion in the wrong place. This should be a topic for Planning Council meeting.

**Comment by cdietrich** [comment]
@merks  could you take this one up?

**Comment by merks** [comment]
@jonahgraham FYI

I think the general point here is that we still have the following existing "must do rule" that has never been removed, although the Platform is no longer following this rule:

https://wiki.eclipse.org/SimRel/Simultaneous_Release_Requirements#Re-use_and_share_common_third_party_code_.28partially_tested.29

Of course ultimately the point of the rule is to avoid duplication and incompatibility of requirements, so likely we should focus on those points first and foremost.  That goal has become somewhat more challenging because now we (everyone else) must all try to use what the platform is using and redistributing (and that's been chaotically changing these last weeks).  That being said, this scenario is not really so totally different from before where we all needed to consume from Orbit and hence accommodate whatever changes Orbit was  releasing.

@cdietrich 

I'm not sure ultimately your goal/desire.  You'd like a repository other than the platform's repository that contains a subset of what's in the platform's repository so that you can consume from that instead of from the platform's repository?

Note that if you look in the report that's generated nightly

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.25-I-builds/index.html

You can see all the PGP signed content that is coming directly from Maven:

![image](https://user-images.githubusercontent.com/208716/183443456-c2084afa-f0be-494d-a10e-ff0737c25e9f.png)

**Comment by cdietrich** [comment]
i just want to avoid duplicate work done by different project leading to same thing in sightly different versions in the repo so that all kind of wired side effects might occur.

i also have understood projects should not pull random stuff vom random repositories e.g lets say project xyz has library abc and we at xtext want to consume abc so we introduce abc

it is also unclear to me what needs to be done to get maven only stuff into our repo and what to the current sign & deploy needs to be changed. i know there is the google doc but i does not really help me. i also dont know how i can test it all all. 

the good thing about orbit was the infrastructure had to be created once and one pr had to be done for 1 lib and that was it.

and i see a gazillion of project having the same problem, but they dont seem to care yet or not stumble on it yet.

**Comment by merks** [comment]
> i just want to avoid duplicate work done by different project leading to same thing in sightly different versions in the repo so that all kind of wired side effects might occur.
> 

Yes, it would be nice to avoid duplicate work.  It seems to me though that one often needs to modify a *.target file, a feature.xml, or a MANIFEST.MF to accommodate "upstream" version changes.  That issue doesn't change no matter how the upstream content/source is managed, does it?  With regard to pulling directly from Maven, that's mostly an issue of modifying the *.target to pull a new version.   I don't think pulling directly the same version from Maven multiple different times creates slightly different versions though...

> i also have understood projects should not pull random stuff vom random repositories e.g lets say project xyz has library abc and we at xtext want to consume abc so we introduce abc
> 

Yes, though what the platform is doing isn't random.  Yes, it's been rather chaotic, but, going forward I expect the platform will generally try to pull in the **latest** version of its dependencies directly from maven, and Maven central is a random repository.  So that seems pretty clear.  @akurtakov has argued in the past that one way to avoid duplicates is to have everyone always use the latest of each dependency, which strikes me as sound reasoning.  (Yes, those could come from Orbit and be centrally managed.)

> if directly consume maven is "the thing" why cannot orbit do it and stay available as it is.
> 

It could me managed that way, but who will do all the work to establish and maintain that?  In the end, I'd rather not maintain a whole whack of infrastructure.   It seems to me that all we really need is a list of Maven coordinates, exactly like we see in the *.target file with maven locations.   So you're basically kind of asking for some type of single centralized *.target file from which an single Orbit p2 repository would be built, with PGP signed bundles, and we'd all edit that thing directly in some coordinated way.

> it is also unclear to me what needs to be done to get maven only stuff into our repo and what to the current sign & deploy needs to be changed. i know there is the google doc but i does not really help me. i also dont know how i can test it all all.
> 

I can help with that if you are really wanting to do that.  Do you?  I have already tried to help by sharing a project for building a repository with PGP signed content from a simple target platform with maven location.  

You can also look at the commits I did to enable this for WindowBuilder:

https://github.com/eclipse/windowbuilder/commits/master

> the good thing about orbit was the infrastructure had to be created once and one pr had to be done for 1 lib and that was it.
> 
> and i see a gazillion of project having the same problem, but they dont seem to care yet or not stumble on it yet.

Yes, I wonder what everyone else is doing too.  There is a lot of stale old content and folks don't seem very communicative...
